### PR TITLE
Associate WAF ACL

### PR DESCRIPTION
**Pull request by masterzen**
Hi,

This PR is a work on top of @athal7 #214 PR, which aim to fix the panic and finish the work. I couldn't contribute to @athal7's original PR, so I had to open a new one.

It is rebased on top of latest master and has been proof-tested on a live aws k8s cluster.

It would awesome if any of you could take the time to review it and possibly merge it.
Let me know if there's anything I need to do.

Thanks,
Brice

### CODE REVIEW

**Comment by joshrosso** [comment]
@bigkraig -- I'd like to test for regressions in our environment (since we don't use WAF) and merge as is (after solving some conflicts) .

Given it's being used in production (https://github.com/coreos/alb-ingress-controller/issues/211#issuecomment-360064356)

That cool w/ you?

Otherwise, if you've got bandwidth to do some WAF validation, that'd even better.

**Comment by bigkraig** [comment]
cool with me. i dont really have WAF experience to test against. i

**Comment by kodytrinnier** [comment]
Just checking to see if there has been any success in testing this? Would love to use this functionality!

**Comment by masterzen** [comment]
@kodytrinnier as I said in the original ticket, we're using this patch along with #279 in production for more than 3 months now without any (apparent) issue.
Of course YMMV.

**Comment by masterzen** [comment]
@bigkraig I will rebase and fix conflicts ASAP.
I'll add a check in `delete` at the same time.

**Pull request merged**
