### PR TITLE
Fix typo in controller-deployment.yaml

### PR DESCRIPTION
**Pull request by edude03**

### CODE REVIEW

**Comment by yuriipolishchuk-finsight** [comment]
Actually it's not a typo but a bug.

Got an error without this fix:
```
Error: parse error in "alb-ingress-controller-helm/templates/controller-deployment.yaml": template: alb-ingress-controller-helm/templates/controller-deployment.yaml:64: unexpected {{end}}
```
Please merge it.

**Comment by yuriipolishchuk** [comment]
Actually it's not a typo but a bug.

Got an error without this fix:

Error: parse error in "alb-ingress-controller-helm/templates/controller-deployment.yaml": template: alb-ingress-controller-helm/templates/controller-deployment.yaml:64: unexpected {{end}}
Please merge it.

**Comment by kjackson87** [comment]
This is a duplicate of #354

**Comment by bigkraig** [comment]
thanks, i just merged #354

**Pull request closed without merging**
