### PR TITLE
Support ALB IpAddressType (IPv6) via a new annotation

### PR DESCRIPTION
**Pull request by danopia**
`ipv4` is AWS’s default value, and this annotation allows upgrading to
`dualstack` or sticking with no value (aka `ipv4`)

* Annotation key: `alb.ingress.kubernetes.io/ip-address-type`
* Default value: `ipv4` (as per AWS)
* Possible other value: `dualstack`
* ALBs can be modified without recreation

I've done minimal testing of this in my own clusters by adding the new annotation to an existing ingress. Please note that you have to add IPv6 prefixes to your VPC and the subnets holding your ALBs before `dualstack` will work.

### CODE REVIEW

**Comment by aledbf** [comment]
@danopia please check https://github.com/kubernetes/kubernetes/issues/49753

**Comment by danopia** [comment]
@aledbf that ticket concerns the `Type: LoadBalancer` ELB support built into Kubernetes, right? Which is separate from using the alb-ingress-controller from this repository. Kubernetes itself doesn't maintain these ALBs, so it's not responsible for enabling IPv6 on them.

I looked at the Travis CI failure and it seems like it's missing some configuration to run the test suite. I did add a new test but it doesn't seem to be the problem. `flag needs an argument: -repotoken`

**Comment by joshrosso** [comment]
That's correct. This repo is an ingress controller implementation for ALBs, independent of Kubernete's AWS integration (specifically for ELBs).

Thanks for the PR, we'll review and test in short order. The failing Trais CI tests are not your fault, something on our backlog to correct.

**Comment by danopia** [comment]
Thanks for the confirmation.

I have since realized this doesn't manage adding AAAA records in Route53. For my specific usecase I've been manually aliasing DNS, so I didn't think of it.

**Comment by montyz** [comment]
I could really use this IPV6 support, but I don't understand GitHub well enough to know how to edit the doc file and attach it to this PR. Here is my suggestion for updating the docs. Use or modify as you see fit.

- **ip-address-type**: Defines whether an ALB should be `ipv4` or `dualstack`. See [IP Address Type](http://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#ip-address-type) in the AWS documentation for more details. Note that to support IPv6, you will also have to add an IPv6 CIDR to your VPC, Subnet, Route Table, Network ACLs (maybe, by default they seem to allow IPv6 traffic), and Security Group Inbound Rules. [Troubleshooting Connecting to Your Instance](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/TroubleshootingInstancesConnecting.html#TroubleshootingInstancesConnectionTimeout) may be of help if you are getting connection timeouts.

as markdown:

```
- **ip-address-type**: Defines whether an ALB should be `ipv4` or `dualstack`. See [IP Address Type](http://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#ip-address-type) in the AWS documentation for more details.
Note that to support IPv6, you will also have to add an IPv6 CIDR to your VPC, Subnet, Route Table, Network ACLs (maybe, by default they seem to allow IPv6 traffic), and Security Group Inbound Rules.
[Troubleshooting Connecting to Your Instance](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/TroubleshootingInstancesConnecting.html#TroubleshootingInstancesConnectionTimeout) may be of help if you are getting connection timeouts.

```
Here it is as a patch if that is helpful:

    Index: docs/ingress-resources.md
    IDEA additional info:
    Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
    <+>US-ASCII
    ===================================================================
    --- docs/ingress-resources.md	(revision 4e75ce0736da84b64f6d5213ad0a6be0fd766626)
    +++ docs/ingress-resources.md	(revision )
    @@ -64,6 +64,7 @@
     alb.ingress.kubernetes.io/unhealthy-threshold-count
     alb.ingress.kubernetes.io/listen-ports
     alb.ingress.kubernetes.io/scheme
    +alb.ingress.kubernetes.io/ip-address-type
     alb.ingress.kubernetes.io/successCodes
     alb.ingress.kubernetes.io/tags
     ```
    @@ -92,6 +93,10 @@
     
     - **scheme**: Defines whether an ALB should be `internal` or `internet-facing`. See [Load balancer scheme](http://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/how-elastic-load-balancing-works.html#load-balancer-scheme) in the AWS documentation for more details.
     
    +- **ip-address-type**: Defines whether an ALB should be `ipv4` or `dualstack`. See [IP Address Type](http://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#ip-address-type) in the AWS documentation for more details.
    +Note that to support IPv6, you will also have to add an IPv6 CIDR to your VPC, Subnet, Route Table, Network ACLs (maybe, by default they seem to allow IPv6 traffic), and Security Group Inbound Rules.
    +[Troubleshooting Connecting to Your Instance](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/TroubleshootingInstancesConnecting.html#TroubleshootingInstancesConnectionTimeout) may be of help if you are getting connection timeouts.
    +
     - **successCodes**: Defines the HTTP status code that should be expected when doing health checks against the defined `healthcheck-path`. When omitted, `200` is used.
     
     - **tags**: Defines [AWS Tags](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html) that should be applied to the ALB instance and Target groups.

**Comment by vinceprignano** [comment]
Is this still in progress?

**Comment by joshrosso** [comment]
@vinceprignano not at the moment.

We dropped the ball on getting it merged in time. Right now our focus is on #197.

Once that's done, we'll work to get this merged into the newest code path for a future release.

**Comment by joshrosso** [comment]
Closing this PR for now as we let it fall through the cracks. Would love to get it in if someone can rebase against current master!

**Comment by lareeth** [comment]
@danopia Would you be able to rebase and either update this, or create a new pull request? I'm very interested in having this feature available.

**Comment by lareeth** [comment]
@danopia I have rewritten this to work with the latest code. You can see my pull request here: https://github.com/coreos/alb-ingress-controller/pull/317

**Pull request closed without merging**
