### PR TITLE
Update vendored dependencies to work towards kubernetes 1.6 compatibility

### PR DESCRIPTION
**Pull request by cmaloney**
Currently trying to run this with a kops 1.6.0-beta.1 deployed kubernetes 1.6.0 cluster and getting quite a bit of odd behavior.  This is my work towards fixing that

Some of the things seen
 - Ingresses being updated but the ALB ingress controller not having it's OnUpdate event fire.
 - Weirdness in syncing the rules (Some rules appear, some don't. Some point to the wrong service. All targets exist)

Hope is to update the vendored library to hopefully fix the update issues (The kubernetes/ingress repo changed the kubernetes go client version), and then work on the issues around syncing rules.

### CODE REVIEW

**Comment by cmaloney** [comment]
@joshrosso this should be ready to go / shouldn't break existing things while slightly improving kubernetes 1.6 readiness

**Comment by joshrosso** [comment]
Thanks @cmaloney, will review this week.

**Comment by joshrosso** [comment]
@cmaloney haven't had a ton of time to dig in, but I seem to be unable to build even after killing of my glide cache and vendor folder.

```
$ make clean && make && make push
rm -f server
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOARM=6 go build -a -installsuffix cgo -ldflags '-w' -o server ./main.go
# github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/annotations/authreq
vendor/k8s.io/ingress/core/pkg/ingress/annotations/authreq/main.go:134: ur.Hostname undefined (type *url.URL has no field or method Hostname)
make: *** [Makefile:28: server] Error 2
```

I did do a rebase, so perhaps I borked something. Going to dig in further when I have a moment, let me know if the build works ok for you.

**Comment by joshrosso** [comment]
Ah, it's coming from the `net` pkg, might just be go version differences.

**Comment by joshrosso** [comment]
Yup, https://golang.org/doc/go1.8#net_url.

Need to refine the build process soon. Anyways, testing now.

**Comment by joshrosso** [comment]
@cmaloney, passes in my 1.6.1 cluster. Thanks for the contribution!

**Pull request merged**
