### PR TITLE
Stabilization and move toward 1.0

### PR DESCRIPTION
**Pull request by joshrosso**
This PR represents our move to 1.0 of the alb-ingress-controller. Specifically addressing clean up and stabilization.

- [x] Docs updated to reflect HBR
- [x] Walkthrough example of new alb-ingress-controller
- [x] Address all panic-related issues
- [x] Exclude master nodes from ALB targets
- [x] Include AWS background sync (https://github.com/coreos/alb-ingress-controller/pull/185)
- [x] Include host based routing

## Issue burn-down list
- [x] Ignore master nodes: https://github.com/coreos/alb-ingress-controller/issues/92
- [x] Ingress controller sets status even if alb creation doesn't succeed: 
https://github.com/coreos/alb-ingress-controller/issues/191
- [x] Targetgroups no longer update when changes to nodelist occur: https://github.com/coreos/alb-ingress-controller/issues/204
- [x] Determine ALB subnets based on tags if annotation is not provided: https://github.com/coreos/alb-ingress-controller/issues/7
- [x] Create security group if annotation is not provided: https://github.com/coreos/alb-ingress-controller/issues/6
- [x] Lock controller when syncing with AWS or Reconciling: https://github.com/coreos/alb-ingress-controller/issues/209
- [x] cluster name cannot contain dash (-): https://github.com/coreos/alb-ingress-controller/issues/198
- [x] Event API seems to no longer be propagating correctly: https://github.com/coreos/alb-ingress-controller/issues/216
- [x] Update iam-policy based on 1.0 controller: https://github.com/coreos/alb-ingress-controller/issues/217
- [x] AWS Background Sync causes ingress statuses to flush: https://github.com/coreos/alb-ingress-controller/issues/220
- [x] Cached annotation errors do not create events: https://github.com/coreos/alb-ingress-controller/issues/230
- [x] Event API seems to no longer be propagating correctly: https://github.com/coreos/alb-ingress-controller/issues/216
- [x] Only HTTPS active despite we've set them both in the alb.../port annotation: https://github.com/coreos/alb-ingress-controller/issues/194
- [x] controller does not respect alb.ingress.kubernetes.io/security-groups annotation: https://github.com/coreos/alb-ingress-controller/issues/232

### CODE REVIEW

**Comment by antoniobeyah** [comment]
Does this work include getting the chart on quay.io updated?

**Comment by joshrosso** [comment]
@antoniobeyah it does now, thanks.

**Comment by joshrosso** [comment]
Checking off ignore master nodes, as only workers are now being picked up.

1 worker 2 master cluster:
image

targetgroups on ALB only contain worker:
image

Again, masters are qualified by the `node-role.kubernetes.io/master` label.

```
$ kubectl get nodes -L=node-role.kubernetes.io/master
NAME                                        STATUS    AGE       VERSION           MASTER
ip-10-0-29-222.us-east-2.compute.internal   Ready     1h        v1.7.2+coreos.0   
ip-10-0-66-11.us-east-2.compute.internal    Ready     1h        v1.7.2+coreos.0   <none>
ip-10-0-7-65.us-east-2.compute.internal     Ready     1h        v1.7.2+coreos.0   
```

**Comment by joshrosso** [comment]
Status updates no longer occur when reconcile fails, but will continue once it succeeds again.

Example in failure:
```
E0913 11:04:09.946830   22408 albingress.go:158] [ALB-INGRESS] [echoserver/echoserver] [ERROR]: Error instantiating target groups: Unable to find the echoserver/echoserver2 service
I0913 11:04:09.946901   22408 controller.go:432] ingress backend successfully reloaded...
W0913 11:04:13.278950   22408 controller.go:869] error obtaining service endpoints: service echoserver/echoserver2 does not exist
I0913 11:04:13.279646   22408 controller.go:423] backend reload required
```

Once issue is resolved in ingress resource:

```
I0913 11:05:34.215193   22408 rule.go:127] [ALB-INGRESS] [echoserver/echoserver] [INFO]: Start Rule modification.
I0913 11:05:34.318401   22408 rule.go:134] [ALB-INGRESS] [echoserver/echoserver] [INFO]: Completed Rule modification. Rule Priority: "1" | Condition: [{    Field: "host-header",    Values: ["echo.josh-test-dns.com"]  },{    Field: "path-pattern",    Values: ["/"]  }]
I0913 11:05:34.318546   22408 controller.go:432] ingress backend successfully reloaded...
I0913 11:05:51.757911   22408 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"echoserver", Name:"echoserver", UID:"bee86050-989a-11e7-86eb-06dbb374bd68", APIVersion:"extensions", ResourceVersion:"22530", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress echoserver/echoserver
I0913 11:05:54.301478   22408 status.go:347] updating Ingress echoserver/echoserver status to [{ test-echoserver-echoserver-2ad7-1990379304.us-east-2.elb.amazonaws.com}]
I0913 11:05:54.458244   22408 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"echoserver", Name:"echoserver", UID:"bee86050-989a-11e7-86eb-06dbb374bd68", APIVersion:"extensions", ResourceVersion:"22545", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress echoserver/echoserver
```

**Comment by joshrosso** [comment]
Targetgroups (and other AWS checks) will now update on at least a 3 minute interval. We do this by ensure that if the OnUpdate callback hasn't fired in 180 seconds, it is called from the controller in a separate go routine. Logs are as follows.

```
[ALB-INGRESS] [controller] [DEBUG]: Forcing ingress update as update hasn't been seen in 3 minutes.
```

**Comment by antoniobeyah** [comment]
@joshrosso Excellent work here.  Two questions:

- Are PRs still currently being accepted?  Some of the items listed below I think I can tackle but I want to make sure it is worth the effort.
- Do you have an idea of a when you would expect 1.0 to be ready?

Things I would like to see as an MVP for 1.0 as these are essentially showstoppers from it being used:
- Ability to configure access logging [#90] - This is a basic security requirement
- Allow dash in cluster name or explain why its not allowed given cluster name is determined before the controller has been installed [#198]
- Helm chart on quay.io out of date [#193] - we performed a workaround and published the chart to our private repository

Also, I ran into a bug where the controller did not detect changes to annotations and it required a controller restart in order to get it to correct.  I haven't tested against these latest commits but will give that a shot and file an issue if it still remains.

**Comment by joshrosso** [comment]
> Are PRs still currently being accepted? Some of the items listed below I think I can tackle but I want to make sure it is worth the effort.

Definitely. I've pinged you in k8s slack. Let's discuss more granular when you have a moment.

> Do you have an idea of a when you would expect 1.0 to be ready?

Before 09/26 is ideal for me as I'll be on vacation after that :)

All issues you've mentioned are reasonable, but I'd ask that you take on #90 and possible #198 if possible.

**Comment by joshrosso** [comment]
Automated subnet detect for qualified subnets (based on tags) is now implemented in https://github.com/coreos/alb-ingress-controller/pull/197/commits/4f00ac6ed34ae5fd63f76a74f0118095229df451.

**Comment by joshrosso** [comment]
@matt-deboer Your commits have been brought in for the AWS sync. Thanks again for the work!

AFAICT: We have introduced a new issue that may require some additional locking on the controller. Specifically, it appears that the controller could be mid-reconcile when the AWS-sync kicks off and thus have the `ALBIngresses` swapped out from underneath them.

I'll tackle it in https://github.com/coreos/alb-ingress-controller/issues/209.

**Comment by joshrosso** [comment]
@matt-deboer Awesome -- let me know if you have time to tackle today and it's yours. Otherwise I'll try to knock it out.

**Comment by matt-deboer** [comment]
there you go...https://github.com/coreos/alb-ingress-controller/pull/210

**Comment by antoniobeyah** [comment]
@joshrosso I am starting on #90 today

**Comment by joshrosso** [comment]
rgr @antoniobeyah; thanks!

**Comment by joshrosso** [comment]
end-to-end walkthrough, including `external-dns` usage can be found at https://github.com/coreos/alb-ingress-controller/blob/continued_stabilization/docs/walkthrough.md

Let me know if you have any feedback.

**Comment by joshrosso** [comment]
I want to get the rest of the issue burn down list covered then merge into master cutting an `1.0-alpha.3` build.

**Comment by joshrosso** [comment]
Bringing this PR into master now assuming tests pass. As noted at the top of the README, we'll cut an alpha slice and would all issues should note the version being used.

**Pull request merged**
