### PR TITLE
#92 Ignore master nodes

### LINKED ISSUE #92: Stop using master nodes
Stop master nodes being added to the target group. Master nodes should not handle this traffic.

### PR DESCRIPTION
**Pull request by owenhaynes**
Removes master nodes from registered instances.

Resolves #92

### CODE REVIEW

**Comment by treyhyde** [comment]
The logic for Service: LoadBalancer in kube aws is to exclude nodes that are marked with SchedulingDisabled which usually includes the masters.  I think that covers a broader range of cases.  This PR will still probably include cordoned nodes in the pool for instance.

**Comment by owenhaynes** [comment]
Don't mind changing it to scheduling disabled. Will give it a test

**Comment by owenhaynes** [comment]
so check for the following taints on the nodes:
node-role.kubernetes.io/master:NoSchedule
node-role.kubernetes.io/node:NoSchedule
?

**Comment by treyhyde** [comment]
I understand there are some mechanical differences between NodeNotSchedulable not 1.5 and and the more mature taints in 1.6.  I'm looking at my 1.5 cluster right now, and marking a node as not schedulable doesn't' seem to add a taint or an annotation.


re kops, there was some healthy discussion about taints and marking masters as schedulable or not... I can't find it right now.  Maybe both approaches are warranted.

**Comment by joshrosso** [comment]
Hi @treyhyde @owenhaynes 

The exclusion of master nodes makes sense. Can we reach consensus on what annotations are required for 1.5+ as discussed above and add them into this PR?

Thanks for the work, looking forward to merging this!

**Comment by joshrosso** [comment]
@owenhaynes @treyhyde 

Ping on this. Does it make sense to simply detect both annotations?

Or is there only 1 you feel we need. Most of the deployments i'm testing against are self-hosted k8s so the same principals don't apply. Would love to have this if it helps compatibility with kops and similar.

**Comment by darkofabijan** [comment]
Would love to see solution for this :) Exposing masters in this way seems like a pretty bad idea.

**Comment by miry** [comment]
is it possible to have node selector? ideally I would like to have registered nodes where my containers are running. instead of include all nodes.

**Comment by joshrosso** [comment]
@miry for the near term, we're planning to go with what's described here: https://github.com/coreos/alb-ingress-controller/pull/197/commits/32655dfc057bfad61f45bee670ad1e97bb997fab

**Pull request closed without merging**
