### PR TITLE
WIP Associate WAF ACL.

### PR DESCRIPTION
**Pull request by athal7**

### CODE REVIEW

**Comment by athal7** [comment]
@joshrosso I think I'm getting somewhere here with re-working https://github.com/coreos/alb-ingress-controller/pull/115 off of continued_stabilization. It looks like the tests have passed, and there's an error with goveralls token. Do you have any time to 👀 ?

**Comment by joshrosso** [comment]
@bigkraig I know you were a bit closer to the goveralls work.

Any idea what the token issue is? Seems to be related to when PR source is fork rather than branch on this repo.

If not, i'll investigate soon.

**Comment by joshrosso** [comment]
@athal7 Have you tested this in k8s? Or is there still work to be done integrating it?

Just checking to see if you need a review / testing of the code itself.

**Comment by athal7** [comment]
@joshrosso I am not an admin on our k8s cluster, so if you don't mind checking out the functionality as well that'd be super helpful

**Comment by joshrosso** [comment]
It's going to be a bit before I can test this (need to research WAF and such as i've not made use of it in AWS previously).

Is this ready to test though or do you feel there's still work to do from a code perspective?

**Comment by athal7** [comment]
From what I can tell it’s ready to be tested. 

In case it helps at all, I think the level of verification can be scoped to whether the wafacl resource gets associated to the alb (which can be seen in the waf section of the aws console). The functionality of the waf rules themselves probably don’t need verification.

**Comment by bigkraig** [comment]
I just pushed 2f7fd3019a9cc1583071757c2cfeabb3dc8f490d which will ignore the goveralls update errors on forks. :+1:

**Comment by joshrosso** [comment]
Thanks @athal7.

Little weekend project for me to read up and see if I can test this against my own cluster.

**Comment by athal7** [comment]
@joshrosso just checking in on this one, thanks!

**Comment by athal7** [comment]
@joshrosso any luck?

**Comment by bigkraig** [comment]
@atha7 I blocked off part of my calendar to test this out tomorrow :+1:

**Comment by masterzen** [comment]
Hi all,

I've been checking this PR because we badly needed the functionnality, and unfortunately this work is not complete (it panics at start, then after the panic has been solved, I discovered that the loadbalancer reconciliation didn't call the WAF association code, so no WAF associations were applied).

I've finished the work for our use case and validated that it works on our live k8s cluster. Since I can't contribute to this PR directly, I've open a new one: PR #278.

Please let me know if there's anything I need to do.
Thanks
Brice

**Comment by bigkraig** [comment]
i've closed this out in favor of #278

**Pull request closed without merging**
